apiVersion: v1
kind: Pod
metadata:
  name: nodejs-server-pod
spec:
  containers:
    - name: nodejs-server-container
      image: hishamahammedkm/node-server
      ports:
        - containerPort: 3000
      command:  [ "node", "server.js" ]
      workingDir: /app
  #     volumeMounts:
  #       - name: app-volume
  #         mountPath: /app
  # volumes:
  #   - name: app-volume
      # configMap:
      #   name: nodejs-server-configmap
      #   items:
      #     - key: server.js
      #       path: server.js
      #     - key: package.json
      #       path: package.json
      #     - key: package-lock.json
      #       path: package-lock.json