# name: ci

# on:
#   push:
#     branches:
#       - "k8s"

# jobs:
#   docker:

#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-action-tst:latest
#   deploy:
#     runs-on: self-hosted
#     steps:
#         - name: Checkout code
#           run: cd command

name: Move and restart Docker Compose

on:
  push:
    branches: [ k8s ]

jobs:
  move_and_restart:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # - name: Move folder
      #   run: |
      #     SOURCE_DIR="/path/to/source/directory"
      #     DEST_DIR="/path/to/destination/directory"
      #     mv "$SOURCE_DIR" "$DEST_DIR"
      
      - name: Restart Docker Compose
        run: |
          cd /home/ubuntu/samskara/test
          docker-compose down
          docker image rm hishamahammedkm/samskara-sever -f
          docker-compose up -d
